import React from 'react';
import SvgIcon from './SvgIcon';

const icon = (type, displayName) => {
  const Icon = props => <SvgIcon type={type} {...props} />;

  Icon.displayName = `Icons.${displayName}`;
  return Icon;
};

const Icons = props => <SvgIcon {...props} />;

Object.assign(Icons, {
  Add: icon('add', 'Add'),
  AddNote: icon('addNote', 'AddNote'),
  Advisory: icon('advisory', 'Advisory'),
  Allocate: icon('allocate', 'Allocate'),
  Approve: icon('approve', 'Approve'),
  Archive: icon('archive', 'Archive'),
  ArrowLeft: icon('arrowLeft', 'ArrowLeft'),
  ArrowRight: icon('arrowRight', 'ArrowRight'),
  AutoAllocation: icon('autoAllocation', 'AutoAllocation'),
  Bank: icon('bank', 'Bank'),
  BankFeeds: icon('bankFeeds', 'BankFeeds'),
  BarChart: icon('barChart', 'BarChart'),
  Binoculars: icon('binoculars', 'Binoculars'),
  BookKeeper: icon('bookKeeper', 'BookKeeper'),
  Budgets: icon('budgets', 'Budgets'),
  Business: icon('business', 'Business'),
  Calculator: icon('calculator', 'Calculator'),
  Calendar: icon('calendar', 'Calendar'),
  Caret: icon('caret', 'Caret'),
  CashMoney: icon('cashMoney', 'CashMoney'),
  Chart1: icon('chart1', 'Chart1'),
  Chart2: icon('chart2', 'Chart2'),
  Clock: icon('clock', 'Clock'),
  Close: icon('close', 'Close'),
  CloudDisconnected: icon('cloudDisconnected', 'CloudDisconnected'),
  Cloud: icon('cloud', 'Cloud'),
  Collapse: icon('collapse', 'Collapse'),
  Comments: icon('comments', 'Comments'),
  Compliance: icon('compliance', 'Compliance'),
  Copy: icon('copy', 'Copy'),
  Cross: icon('cross', 'Cross'),
  Delete: icon('delete', 'Delete'),
  Dollar: icon('dollar', 'Dollar'),
  DownChevron: icon('downChevron', 'DownChevron'),
  DownChevronLarge: icon('downChevronLarge', 'DownChevronLarge'),
  Download: icon('download', 'Download'),
  Drivers: icon('drivers', 'Drivers'),
  Edit: icon('edit', 'Edit'),
  EndArrowLeft: icon('endArrowLeft', 'EndArrowLeft'),
  EndArrowRight: icon('endArrowRight', 'EndArrowRight'),
  Error: icon('error', 'Error'),
  Expand: icon('expand', 'Expand'),
  Feedback: icon('feedback', 'Feedback'),
  File: icon('file', 'File'),
  Filter: icon('filter', 'Filter'),
  Finance: icon('finance', 'Finance'),
  Flag: icon('flag', 'Flag'),
  FolderEdit: icon('folderEdit', 'FolderEdit'),
  FolderLocked: icon('folderLocked', 'FolderLocked'),
  Folder: icon('folder', 'Folder'),
  GenerateReport: icon('generateReport', 'GenerateReport'),
  GenericDocument: icon('genericDocument', 'GenericDocument'),
  Glossary: icon('glossary', 'Glossary'),
  GridView: icon('gridView', 'GridView'),
  Help: icon('help', 'Help'),
  Hints: icon('hints', 'Hints'),
  History: icon('history', 'History'),
  HomeIcon: icon('homeIcon', 'HomeIcon'),
  Image: icon('image', 'Image'),
  InProgress: icon('inProgress', 'InProgress'),
  Info: icon('info', 'Info'),
  Inventory: icon('inventory', 'Inventory'),
  Invoice: icon('invoice', 'Invoice'),
  Keyboard: icon('keyboard', 'Keyboard'),
  Landline: icon('landline', 'Landline'),
  LaptopComputer: icon('laptopComputer', 'LaptopComputer'),
  LeftChevron: icon('leftChevron', 'LeftChevron'),
  LineChart: icon('lineChart', 'LineChart'),
  Linked: icon('linked', 'Linked'),
  ListView: icon('listView', 'ListView'),
  Location: icon('location', 'Location'),
  Lock: icon('lock', 'Lock'),
  Magnify: icon('magnify', 'Magnify'),
  Mail: icon('mail', 'Mail'),
  Minify: icon('minify', 'Minify'),
  Mobile: icon('mobile', 'Mobile'),
  More: icon('more', 'More'),
  Move: icon('move', 'Move'),
  Navigation: icon('navigation', 'Navigation'),
  NewFeature: icon('newFeature', 'NewFeature'),
  Notifications: icon('notifications', 'Notifications'),
  OpenExternalLink: icon('openExternalLink', 'OpenExternalLink'),
  PcComputer: icon('pcComputer', 'PcComputer'),
  Pin: icon('pin', 'Pin'),
  PoweredBy: icon('poweredBy', 'PoweredBy'),
  PrintEd: icon('printEd', 'PrintEd'),
  Purchases: icon('purchases', 'Purchases'),
  Refresh: icon('refresh', 'Refresh'),
  Reject: icon('reject', 'Reject'),
  Reminder: icon('reminder', 'Reminder'),
  ReopenedDocument: icon('reopenedDocument', 'ReopenedDocument'),
  Remove: icon('remove', 'Remove'),
  Replied: icon('replied', 'Replied'),
  RightChevron: icon('rightChevron', 'RightChevron'),
  Save: icon('save', 'Save'),
  Search: icon('search', 'Search'),
  Security: icon('security', 'Security'),
  Settings: icon('settings', 'Settings'),
  SharedWith: icon('sharedWith', 'SharedWith'),
  Show: icon('show', 'Show'),
  Signature: icon('signature', 'Signature'),
  SignOut: icon('signOut', 'SignOut'),
  Sort: icon('sort', 'Sort'),
  Star: icon('star', 'Star'),
  Success: icon('success', 'Success'),
  Switch: icon('switch', 'Switch'),
  Table: icon('table', 'Table'),
  Tag: icon('tag', 'Tag'),
  TasksReopened: icon('tasksReopened', 'TasksReopened'),
  Tasks: icon('tasks', 'Tasks'),
  Tax: icon('tax', 'Tax'),
  Template: icon('template', 'Template'),
  Tick: icon('tick', 'Tick'),
  UnAllocate: icon('unAllocate', 'UnAllocate'),
  UnLink: icon('unLink', 'UnLink'),
  UpChevron: icon('upChevron', 'UpChevron'),
  UpChevronFilled: icon('upChevronFilled', 'UpChevronFilled'),
  Upload: icon('upload', 'Upload'),
  UserProfile: icon('userProfile', 'UserProfile'),
  UsersFolder: icon('usersFolder', 'UsersFolder'),
  Wallet: icon('wallet', 'Wallet'),
  Warning: icon('warning', 'Warning'),
  BulletList: icon('bulletList', 'BulletList'),
  NumberedList: icon('numberedList', 'NumberedList'),
  Bold: icon('bold', 'Bold'),
  Italic: icon('italic', 'Italic'),
  Underline: icon('underline', 'Underline'),
});

export default Icons;
